services:
  frontend:
    build:
      context: /client
      dockerfile: Dockerfile
    container_name: aconews_client
    restart: always
    ports:
      - 5173:5173
    volumes:
      - ./client:/frontend
      - /client/node_modules
  backend:
    build:
      context: /server
      dockerfile: Dockerfile
    container_name: aconews_server
    restart: always
    ports:
      - 8089:8089
    volumes:
      - ./server:/backend
      - /server/node_modules
